import React from 'react';
import { Sparkles, Brain, CheckCircle2, ShieldAlert, Cpu } from 'lucide-react';
import RiskScore from './RiskScore';

export default function AIExplanation({ explanation, factorBreakdown, riskScore, confidence }) {
  if (!explanation) return null;

  const whyFlagged = explanation.why_flagged || [];
  const correlationStrength = explanation.correlation_strength || 'Strong';
  const behaviouralDeviation = explanation.behavioural_deviation || 'High';
  const resourceSensitivity = explanation.resource_sensitivity || 'High';
  const conf = Math.round(confidence || explanation.confidence || 89);
  const finalRisk = riskScore || explanation.final_risk || 91;
  const engineMode = explanation.engine_mode || 'LOCAL_XAI';

  return (
    <div className="bg-[#0f1422] border border-[#1e293b] rounded-xl p-5 shadow-lg relative overflow-hidden">
      {/* Subtle top indicator */}
      <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500"></div>

      <div className="flex items-center justify-between pb-4 border-b border-slate-800">
        <div className="flex items-center gap-2.5">
          <div className="p-2 bg-blue-950/60 border border-blue-500/40 rounded-lg text-blue-400">
            <Brain className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold font-mono tracking-wide text-slate-100 uppercase flex items-center gap-2">
              WHY THIS INCIDENT WAS PRIORITIZED
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-blue-900/50 text-blue-300 border border-blue-700/50">
                XAI EXPLANATION
              </span>
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Transparent, explainable causal justification generated by CyberNexus AI
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-slate-400">Engine:</span>
          <span className="text-xs font-mono font-semibold px-2 py-0.5 bg-slate-800 border border-slate-700 rounded text-cyan-400">
            {engineMode}
          </span>
        </div>
      </div>

      {/* Itemized Contributing Factors List */}
      <div className="mt-4">
        <div className="text-xs font-mono text-slate-300 font-semibold mb-2 flex items-center gap-1.5">
          <Sparkles className="w-3.5 h-3.5 text-blue-400" />
          KEY CONTRIBUTING ANOMALY VECTORS:
        </div>
        <ul className="space-y-2">
          {whyFlagged.map((item, idx) => (
            <li key={idx} className="flex items-start gap-2.5 text-xs text-slate-200 bg-[#131b2e]/60 p-2 rounded-lg border border-slate-800/80">
              <span className="text-red-400 font-mono font-bold text-sm leading-none mt-0.5">+</span>
              <span className="font-mono text-slate-300">{item.replace(/^\+\s*/, '')}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Structured Metrics Table */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-slate-800 text-xs font-mono">
        <div className="bg-[#131b2e]/50 p-2.5 rounded-lg border border-slate-800">
          <span className="text-slate-400 text-[10px] block uppercase">Correlation Strength</span>
          <span className="text-sm font-bold text-blue-400">{correlationStrength}</span>
        </div>

        <div className="bg-[#131b2e]/50 p-2.5 rounded-lg border border-slate-800">
          <span className="text-slate-400 text-[10px] block uppercase">Behavioural Deviation</span>
          <span className="text-sm font-bold text-amber-400">{behaviouralDeviation}</span>
        </div>

        <div className="bg-[#131b2e]/50 p-2.5 rounded-lg border border-slate-800">
          <span className="text-slate-400 text-[10px] block uppercase">Resource Sensitivity</span>
          <span className="text-sm font-bold text-purple-400">{resourceSensitivity}</span>
        </div>

        <div className="bg-[#131b2e]/50 p-2.5 rounded-lg border border-slate-800">
          <span className="text-slate-400 text-[10px] block uppercase">Model Confidence</span>
          <span className="text-sm font-bold text-emerald-400">{conf}%</span>
        </div>
      </div>

      {/* Formula breakdown */}
      {factorBreakdown && factorBreakdown.contributions && (
        <div className="mt-4 pt-3 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-2 text-[11px] font-mono text-slate-400">
          <span className="text-slate-500">Official Risk Formula Breakdown:</span>
          <div className="flex flex-wrap items-center gap-3">
            <span>Anomaly: <strong className="text-slate-200">+{factorBreakdown.contributions.anomaly_contribution}</strong></span>
            <span>Corr: <strong className="text-slate-200">+{factorBreakdown.contributions.correlation_contribution}</strong></span>
            <span>Behaviour: <strong className="text-slate-200">+{factorBreakdown.contributions.behaviour_contribution}</strong></span>
            <span>Asset: <strong className="text-slate-200">+{factorBreakdown.contributions.sensitivity_contribution}</strong></span>
            <span>Sev: <strong className="text-slate-200">+{factorBreakdown.contributions.severity_contribution}</strong></span>
            <span className="text-red-400 font-bold">= {riskScore}/100</span>
          </div>
        </div>
      )}
    </div>
  );
}
